### ISSUE TITLE
v0.10.0-beta.1 punchlist

### ISSUE THREAD

**Issue by skriss** [heptio/ark#1007]
- [x] finalize / merge changelog (#1003 @skriss, w/reviews from @nrb @wwitzel3 @carlisia )
- [x] finalize / merge goreleaser (#1000 @skriss , w/reviews from @nrb @wwitzel3 @carlisia @ncdc )
- [x] update VSL defaulting to make normal case easier (#997, @carlisia / @skriss )
- [x] docs PRs (@Bradamant3)
  - [x] #1004
  - [x] #1005
  - [x] #1008
- [x] build `v0.10.0-beta.1` docs site (@Bradamant3)
