### ISSUE TITLE
v0.10 punchlist

### ISSUE THREAD

**Issue by skriss** [heptio/ark#1052]
- [x] Locations documentation PR #1050 (@skriss)
- [x] Finalize blog post (@carlisia)
- [x] YAML in tarball PR #1045 (@skriss)
- [x] Pre-signed URL base PR #1006 (@wwitzel3)
- [x] Docs PRs #1023 #1038 (@Bradamant3)
- [x] Docs site build replacing beta site (@Bradamant3)
  - Update `Tutorials` links in nav
  - `Configuration reference` link in nav points to nonexistent page
- [x] Ensure external plugin updates are ready (@nrb @rosskukulinski)
- [x] Multiple volume provider snapshot testing (@skriss)
- [x] Update v0.10 changelog (@skriss)
- [x] ~~Wait for deletion PR #826 (@nrb)~~

**Comment by skriss** [comment]
@Bradamant3 @carlisia @nrb @wwitzel3 my 2 open PRs (#1050 #1045) are waiting on review, so PTAL and provide feedback when you get a chance. Thanks!

**Comment by skriss** [comment]
All pre-v0.10 tasks done, proceeding with release.
