### ISSUE TITLE
[Epic] Backup ownership and sharing

### ISSUE THREAD

**Issue by rosskukulinski** [heptio/ark#726]
**User Stories**

As a cluster administrator, I would like to be able to safely backup from Cluster A and restore into Cluster B.  E.g. 
 * Production cluster backing up hourly, staging cluster restoring from the production backups to maintain a "real-world" environment
 * Production cluster A backing up, hot-standby Production Cluster B restoring on a regular basis

**Features**
- [ ] Add/enforce ownership of backup locations
- [ ] Resolve naming conflicts when importing backups from multiple clusters
- [ ] [Update FAQ re: sharing buckets](https://github.com/heptio/ark/blob/master/docs/faq.md#im-using-ark-in-multiple-clusters-should-i-use-the-same-bucket-to-store-all-of-my-backups)

**Non-Goals**
* Integration with IAM or other authentication/authorization systems

**Notes**

This behavior is currently supported through a `restoreOnly` mode which is prone to user error.
